title: jongsoobae's blog
description: () => ()

url: http://jongsoobae.github.io/
baseurl: "/blog"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about

social:
   github: jongsoobae
   facebook: ocpek2@naver.com
   email: ocpek@nate.com

google_analytics: "UA-58263416-1"
